// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz_oNHOJvaqjt-G0nv_KvjugS9wBvaOsk',
    appId: '1:862163489648:web:1bd7cd88514f05eeedb5b5',
    messagingSenderId: '862163489648',
    projectId: 'sachin-be51e',
    authDomain: 'sachin-be51e.firebaseapp.com',
    storageBucket: 'sachin-be51e.appspot.com',
    measurementId: 'G-2CEKQKJ6TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDImFg7QK8qhzBEw8Ok1bDkUd7DxlCI-VI',
    appId: '1:862163489648:android:60172d6f651e8627edb5b5',
    messagingSenderId: '862163489648',
    projectId: 'sachin-be51e',
    storageBucket: 'sachin-be51e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYAU01knBmX_4qToiAxwbSyzt9Y6itSYk',
    appId: '1:862163489648:ios:1ffa9e58058bf7e7edb5b5',
    messagingSenderId: '862163489648',
    projectId: 'sachin-be51e',
    storageBucket: 'sachin-be51e.appspot.com',
    iosClientId: '862163489648-e9snb9dvda6ig53qskl5sccb15rbftbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWorkSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYAU01knBmX_4qToiAxwbSyzt9Y6itSYk',
    appId: '1:862163489648:ios:1ffa9e58058bf7e7edb5b5',
    messagingSenderId: '862163489648',
    projectId: 'sachin-be51e',
    storageBucket: 'sachin-be51e.appspot.com',
    iosClientId: '862163489648-e9snb9dvda6ig53qskl5sccb15rbftbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWorkSpace',
  );
}
